security:
    encoders:
        AppBundle\Security\User\WebserviceUser:   
            algorithm: sha1
            encode_as_base64: false
            iterations: 1
        #Symfony\Component\Security\Core\User\User: plaintext    
        

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:                         
        webservice:            
            id: webservice_user_provider        

    firewalls:            
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

               
        secured_area_v2:
            pattern:    ^/
            anonymous: ~
            provider: webservice
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /dashboard
                provider: webservice
            logout:
                path:   /logout
                target: /login 
            remember_me:
               key:      "newsecret"
               lifetime: 2592000 # one month
               path:     /
               domain:   ~ # Defaults to the current domain from $_SERVER
               
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }