# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.kernelaction_listener:
       class: AppBundle\Classes\KernelControlerEvent
       tags:
        - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    webservice_user_provider:
       class: AppBundle\Security\User\WebserviceUserProvider
